### ISSUE TITLE
how to calculate Landmark location errors？

### ISSUE THREAD

**Issue by HP192080042** [mpapadomanolaki/Multi-Step-Deformable-Registration#1]
Can you provide the code to calculate Landmark location errors？

![dx](https://user-images.githubusercontent.com/53810832/146937233-ca77be51-63a2-45ac-bb8b-6d4b79aa0435.png)

**Comment by mpapadomanolaki** [comment]
@HP192080042 

Hello,
So for the landmark locations you choose some points on the reference image, along with the corresponding ones on the moving image. Then you have to calculate the errors manually.
For example, I have the following code for some image patches, you click on the image point that you want and the (x,y) pixel coordinates are given on the terminal:

import cv2
import numpy as np

ids = ['38','44','110','135', '205']

#events = [i for i in dir(cv2) if 'EVENT' in i]
#print(events)

refPt = []

#click event function
def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,",",y)
        refPt.append([x,y])
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x)+", "+str(y)
#        cv2.putText(img, strXY, (x,y), font, 0.5, (255,255,0), 2)
        cv2.imshow("image", img)

    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y, x, 0]
        green = img[y, x, 1]
        red = img[y, x, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue)+", "+str(green)+","+str(red)
#        cv2.putText(img, strBGR, (x,y), font, 0.5, (0,255,255), 2)
        cv2.imshow("image", img)


#Here, you need to change the image name and it's path according to your directory

cnt=0
for i in range(0, len(ids)):
  img_list = []
  img = cv2.imread('./results/warped_{}.png'.format(ids[cnt]))

  cv2.imshow("image", img)

 #calling the mouse click event
  cv2.setMouseCallback("image", click_event)

  cv2.waitKey(0)
  cv2.destroyAllWindows()
 
  cnt = cnt+1

**Comment by mpapadomanolaki** [comment]
@HP192080042 

Hello,
So for the landmark locations you have to choose some points on the reference image, and then find the corresponding ones on the moving image.
Then you calculate the errors manually.
For example I use the code that I am attaching. I have some image patches and I click on the points that I want, so that the (x,y) pixel coordinates will appear on the terminal.

**Comment by mpapadomanolaki** [comment]
@HP192080042 

Hello,
So for the landmark locations you have to choose some points on the reference image, and then find the corresponding ones on the moving image.
Then you calculate the errors manually.
For example I use the following code. I have some image patches and I click on the points that I want, so that the (x,y) pixel coordinates will appear on the terminal.


`import cv2
import numpy as np

ids = ['38','44','110','135', '205']

#events = [i for i in dir(cv2) if 'EVENT' in i]
#print(events)

refPt = []

#click event function
def click_event(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x,",",y)
        refPt.append([x,y])
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x)+", "+str(y)
#        cv2.putText(img, strXY, (x,y), font, 0.5, (255,255,0), 2)
        cv2.imshow("image", img)

    if event == cv2.EVENT_RBUTTONDOWN:
        blue = img[y, x, 0]
        green = img[y, x, 1]
        red = img[y, x, 2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue)+", "+str(green)+","+str(red)
#        cv2.putText(img, strBGR, (x,y), font, 0.5, (0,255,255), 2)
        cv2.imshow("image", img)


#Here, you need to change the image name and it's path according to your directory

cnt=0
for i in range(0, len(ids)):
  img_list = []
  img = cv2.imread('./RESULTS/warped_{}.png'.format(ids[cnt]))

  cv2.imshow("image", img)

 #calling the mouse click event
  cv2.setMouseCallback("image", click_event)

  cv2.waitKey(0)
  cv2.destroyAllWindows()
 
  cnt = cnt+1
`

**Comment by mpapadomanolaki** [comment]
@HP192080042 

Hello,
So for the landmark locations you have to choose some points on the reference image, and then find the corresponding ones on the moving image.
Then you calculate the errors manually.
For example I use the code that I am attaching. I have some image patches and I click on the points that I want, so that the (x,y) pixel coordinates will appear on the terminal.

[ar_check.txt](https://github.com/mpapadomanolaki/Multi-Step-Deformable-Registration/files/7756086/ar_check.txt)
